security:
    encoders:
        Tecnotek\Bundle\AsiloBundle\Entity\User:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_EMPLOYEE]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        db_users:
                    entity: { class: TecnotekAsiloBundle:User}
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/admin/login$
            security: false

        admin_area:
            pattern:    ^/admin/
            remember_me:
                key:      "%secret%"
                lifetime: 604800 # 1 week in seconds
                path:     /
                name:     "ADMINISTRATION_AREA"
            form_login:
                check_path: _security_check
                login_path: _admin_login
            logout:
                path:   _admin_logout
                target: _welcome
                success_handler: logout_listener
                invalidate_session: true
                delete_cookies:
                    ADMINISTRATION_AREA: { path: '/', domain: null}

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }