_welcome:
    pattern:  /
    defaults: { _controller: TecnotekAsiloBundle:Public:index }

_admin_secured:
    resource: "@TecnotekAsiloBundle/Controller/SecuredController.php"
    type:     annotation
    prefix:   /admin

_pilar_gamboa_admin:
    resource: "@TecnotekAsiloBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin

_pilar_gamboa_admin_patients:
    resource: "@TecnotekAsiloBundle/Controller/PatientsController.php"
    type:     annotation
    prefix:   /admin

_pilar_gamboa_admin_sports:
    resource: "@TecnotekAsiloBundle/Controller/SportsController.php"
    type:     annotation
    prefix:   /admin

_pilar_gamboa_admin_dance:
    resource: "@TecnotekAsiloBundle/Controller/DanceController.php"
    type:     annotation
    prefix:   /admin

_pilar_gamboa_admin_disease:
    resource: "@TecnotekAsiloBundle/Controller/DiseaseController.php"
    type:     annotation
    prefix:   /admin

_pilar_gamboa_admin_entertainmentActivity:
    resource: "@TecnotekAsiloBundle/Controller/EntertainmentActivityController.php"
    type:     annotation
    prefix:   /admin

_pilar_gamboa_admin_instrument:
    resource: "@TecnotekAsiloBundle/Controller/InstrumentController.php"
    type:     annotation
    prefix:   /admin

_pilar_gamboa_admin_manuality:
    resource: "@TecnotekAsiloBundle/Controller/ManualityController.php"
    type:     annotation
    prefix:   /admin

_pilar_gamboa_admin_music:
    resource: "@TecnotekAsiloBundle/Controller/MusicController.php"
    type:     annotation
    prefix:   /admin

_pilar_gamboa_admin_religion:
    resource: "@TecnotekAsiloBundle/Controller/ReligionController.php"
    type:     annotation
    prefix:   /admin

_pilar_gamboa_admin_roomGame:
    resource: "@TecnotekAsiloBundle/Controller/RoomGameController.php"
    type:     annotation
    prefix:   /admin

_pilar_gamboa_admin_sleepHabit:
    resource: "@TecnotekAsiloBundle/Controller/SleepHabitController.php"
    type:     annotation
    prefix:   /admin

_pilar_gamboa_admin_reading:
    resource: "@TecnotekAsiloBundle/Controller/ReadingController.php"
    type:     annotation
    prefix:   /admin

_pilar_gamboa_admin_spiritualActivity:
    resource: "@TecnotekAsiloBundle/Controller/SpiritualActivityController.php"
    type:     annotation
    prefix:   /admin

_pilar_gamboa_admin_writing:
    resource: "@TecnotekAsiloBundle/Controller/WritingController.php"
    type:     annotation
    prefix:   /admin

_pilar_gamboa_admin_pentions:
    resource: "@TecnotekAsiloBundle/Controller/PentionsController.php"
    type:     annotation
    prefix:   /admin

_pilar_gamboa_admin_patients_pentions:
    resource: "@TecnotekAsiloBundle/Controller/PatientsPentionsController.php"
    type:     annotation
    prefix:   /admin

_pilar_gamboa_admin_activities:
    resource: "@TecnotekAsiloBundle/Controller/ActivitiesController.php"
    type:     annotation
    prefix:   /admin

_pilar_gamboa_admin_results:
    resource: "@TecnotekAsiloBundle/Controller/ResultsController.php"
    type:     annotation
    prefix:   /admin

_pilar_gamboa_admin_patiens_report:
    pattern:  /reports/reportListCatalog/
    defaults: { _controller: TecnotekAsiloBundle:Admin:reportListCatalog }